baseURL = 'https://pawparadise.biz'
languageCode = 'en-us'
title = 'Paw Paradise'
theme = "spectral"

[params]
fancyTitle = '<img height="250px" src="/img/logo.webp" /> <br /> Paw Paradise'
description = "Description of site can go here test"
